from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from deploy.paths import MANAGED_HEADER
from deploy.runner import Runner

SYSTEMCTL = "/usr/bin/systemctl"

UNIT_SUFFIX = ".service"
NGINX_SUFFIX = ".conf"


class ForeignFile(Exception):
    """A file we were about to overwrite was not written by us."""


class NginxTestFailed(Exception):
    """`nginx -t` rejected the new configuration; nothing was reloaded."""


@dataclass(frozen=True)
class Change:
    path: Path
    before: str | None
    after: str | None

    @property
    def is_removal(self) -> bool:
        return self.after is None


def plan_changes(
    desired: dict[Path, str], *, remove: Iterable[Path] = ()
) -> list[Change]:
    """Diff desired state against disk. Writes nothing.

    Raises ForeignFile rather than clobbering anything we did not generate.
    """
    changes: list[Change] = []
    for path, after in sorted(desired.items()):
        before = path.read_text() if path.exists() else None
        if before is not None and not before.startswith(MANAGED_HEADER):
            raise ForeignFile(
                f"{path} was not generated by deploy (no managed header); "
                "move it aside if you want deploy to own it"
            )
        if before != after:
            changes.append(Change(path, before, after))
    for path in sorted(remove):
        if path.exists():
            before = path.read_text()
            if not before.startswith(MANAGED_HEADER):
                raise ForeignFile(f"{path} was not generated by deploy")
            changes.append(Change(path, before, None))
    return changes


def apply_changes(
    changes: list[Change], *, runner: Runner, dry_run: bool = False
) -> set[str]:
    """Write the changes and perform only the reloads they require.

    Returns the set of reload actions performed, for the caller to report.
    """
    if not changes or dry_run:
        return set()

    # Classify by filename suffix, not by substring-matching the path. The
    # path can contain "systemd" or "nginx" incidentally (e.g. a pytest
    # tmp_path derived from a test name), so suffix is the only reliable
    # signal: Paths.unit_file() always produces ".service" and
    # Paths.nginx_file() always produces ".conf".
    touched_units = any(c.path.suffix == UNIT_SUFFIX for c in changes)
    touched_nginx = any(c.path.suffix == NGINX_SUFFIX for c in changes)

    for change in changes:
        if change.is_removal:
            change.path.unlink()
        else:
            change.path.parent.mkdir(parents=True, exist_ok=True)
            change.path.write_text(change.after)

    actions: set[str] = set()

    if touched_nginx:
        # Validate before reloading; on failure put back exactly what was there
        # so a broken render cannot take the site down.
        result = runner.run(["sudo", "nginx", "-t"], check=False)
        if result.returncode != 0:
            _rollback([c for c in changes if c.path.suffix == NGINX_SUFFIX])
            raise NginxTestFailed(result.stderr or "nginx -t failed")
        runner.run(["sudo", SYSTEMCTL, "reload", "nginx"])
        actions.add("nginx")

    if touched_units:
        runner.run(["sudo", SYSTEMCTL, "daemon-reload"])
        actions.add("daemon-reload")

    return actions


def _rollback(changes: list[Change]) -> None:
    for change in changes:
        if change.before is None:
            change.path.unlink(missing_ok=True)
        else:
            change.path.write_text(change.before)
