import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from deploy.paths import (
    ARTIFACT_KINDS,
    MANAGED_HEADER,
    NGINX_SNIPPET,
    SYSTEMD_UNIT,
    ArtifactKind,
    Paths,
)
from deploy.render import Artifact
from deploy.runner import Runner

SYSTEMCTL = "/usr/bin/systemctl"


class ForeignFile(Exception):
    """A file we were about to overwrite was not written by us."""


class ApplyFailed(Exception):
    """Base for failures during apply_changes.

    actions_completed: reloads that DID take effect before the failure.
    unrestored: files rollback could not put back.
    """

    def __init__(
        self,
        message: str,
        *,
        actions_completed: Iterable[str] = (),
        unrestored: Iterable[Path] = (),
    ) -> None:
        super().__init__(message)
        self.actions_completed: set[str] = set(actions_completed)
        self.unrestored: list[Path] = list(unrestored)


class NginxTestFailed(ApplyFailed):
    """`nginx -t` rejected the new configuration; nothing was reloaded."""


class ReloadFailed(ApplyFailed):
    """A reload command itself failed, as opposed to `nginx -t` rejecting the
    config. Distinguished from NginxTestFailed so callers can tell "the new
    config is bad" from "the reload machinery is broken"."""


@dataclass(frozen=True)
class Change:
    path: Path
    before: str | None
    after: str | None
    kind: ArtifactKind

    @property
    def is_removal(self) -> bool:
        return self.after is None


@dataclass(frozen=True)
class OwnedArtifact:
    """A reference to a generated file that exists (or might be removed) on
    disk: its kind and path, with no contents. Distinct from `Artifact`
    (render's output) because a removal has nothing to write — giving it its
    own type keeps "here is text to write" and "here is a file to check for
    and maybe delete" from being conflated."""

    kind: ArtifactKind
    path: Path


def plan_changes(
    desired: Iterable[Artifact], *, remove: Iterable[OwnedArtifact] = ()
) -> list[Change]:
    """Diff desired state against disk. Writes nothing.

    Raises ForeignFile rather than clobbering anything we did not generate.
    """
    changes: list[Change] = []
    for artifact in sorted(desired, key=lambda a: a.path):
        path, after, kind = artifact.path, artifact.contents, artifact.kind
        before = path.read_text() if path.exists() else None
        if before is not None and not before.startswith(MANAGED_HEADER):
            raise ForeignFile(
                f"{path} was not generated by deploy (no managed header); "
                "move it aside if you want deploy to own it"
            )
        if before != after:
            changes.append(Change(path, before, after, kind))
    for owned in sorted(remove, key=lambda o: o.path):
        path, kind = owned.path, owned.kind
        if path.exists():
            before = path.read_text()
            if not before.startswith(MANAGED_HEADER):
                raise ForeignFile(f"{path} was not generated by deploy")
            changes.append(Change(path, before, None, kind))
    return changes


def owned_artifacts(name: str, paths: Paths) -> list[OwnedArtifact]:
    """Every generated file this app currently owns on disk.

    There is no state file: the set of files an app owns is whatever exists
    on disk that this app's naming scheme would produce. This is how a
    re-render notices a file the app used to want but no longer does (e.g.
    it dropped its [nginx] section, or flipped from service to static).

    Iterates ARTIFACT_KINDS rather than a hardcoded candidate list, so a new
    kind is automatically covered here without touching this function.
    """
    candidates = [OwnedArtifact(kind, kind.file(paths, name)) for kind in ARTIFACT_KINDS]
    return [c for c in candidates if c.path.exists()]


def plan_app_changes(
    name: str, desired: Iterable[Artifact], paths: Paths
) -> list[Change]:
    """plan_changes for one app: write/update what it wants, and remove
    whatever it previously owned on disk but no longer wants.

    Callers should prefer this over calling plan_changes directly for a
    single app's desired state — it is the only place that derives what to
    remove, and forgetting to pass `remove` is exactly how a stale unit or
    nginx snippet is left running forever after a rename or a type change.
    """
    desired = tuple(desired)
    desired_paths = {artifact.path for artifact in desired}
    stale = [c for c in owned_artifacts(name, paths) if c.path not in desired_paths]
    return plan_changes(desired, remove=stale)


def _fail_and_rollback(
    exc_type: type[ApplyFailed],
    message: str,
    changes: list[Change],
    *,
    cause: BaseException | None = None,
) -> None:
    """Shared failure path for `nginx -t` and `daemon-reload` rejecting: roll
    back every change made in this call (not just the ones of the kind that
    failed — see apply_changes' docstring), fold any un-restorable paths into
    the message, and raise. Nothing has taken effect yet at either call site
    that uses this, so `actions_completed` is always empty here. Never
    returns normally."""
    unrestored = _rollback(changes)
    if unrestored:
        message += (
            f"; additionally, failed to restore: "
            f"{', '.join(str(p) for p in unrestored)} — check these by hand"
        )
    raise exc_type(message, actions_completed=(), unrestored=unrestored) from cause


def apply_changes(
    changes: list[Change], *, runner: Runner, dry_run: bool = False
) -> set[str]:
    """Write the changes and perform only the reloads they require.

    The disk is the only record of what systemd/nginx have loaded, so any
    failure partway through must leave disk and running state consistent
    with each other — either everything in this call took effect, or nothing
    did. Concretely:

    - Writes happen first, atomically per file. If one write fails, every
      write already made in this call is rolled back and the exception is
      re-raised: no partial write, and no partially-applied change set.
    - Reloads are ordered nginx -t -> daemon-reload -> reload nginx: `nginx
      -t` only validates (nothing to undo), `daemon-reload` is cheap and
      reversible, and reloading nginx is the user-visible, hardest-to-undo
      step, so it goes last, once everything else has already succeeded.
    - A failure at `nginx -t` or `daemon-reload` rolls back *all* the
      changes in this call (not just the nginx ones) before raising, so the
      files on disk go back to exactly matching what systemd/nginx already
      have loaded. That is essential: if only some files were rolled back,
      a later `plan_changes` could find no diff for the ones left in their
      new state and silently believe they'd already been reloaded, even
      though systemd/nginx never saw them.
    - A failure reloading nginx itself happens after `nginx -t` and
      `daemon-reload` have already succeeded, so there is nothing unsafe
      left on disk to roll back; it still raises ReloadFailed so the caller
      knows the reload did not complete — but by now daemon-reload may
      already have taken effect, so that is recorded on
      `actions_completed` rather than lost.

    Returns the set of reload actions performed, for the caller to report.
    """
    if not changes or dry_run:
        return set()

    # Classify by kind identity, not by substring-matching or suffix-matching
    # the path. The path can contain "systemd" or "nginx" incidentally (e.g.
    # a pytest tmp_path derived from a test name), so the kind that produced
    # the change — carried on Change since plan_changes — is the only
    # reliable signal.
    touched_units = any(c.kind is SYSTEMD_UNIT for c in changes)
    touched_nginx = any(c.kind is NGINX_SNIPPET for c in changes)

    _write_changes(changes)

    actions: set[str] = set()

    if touched_nginx:
        # Validate before reloading; on failure put back exactly what was
        # there — for every file this call touched, not only the nginx
        # ones — so a broken render cannot take the site down, and so the
        # rolled-back files remain visible to plan_changes as changes still
        # needing to be applied.
        result = runner.run(["sudo", "nginx", "-t"], check=False)
        if result.returncode != 0:
            _fail_and_rollback(
                NginxTestFailed, result.stderr or "nginx -t failed", changes
            )

    if touched_units:
        try:
            runner.run(["sudo", SYSTEMCTL, "daemon-reload"])
        except subprocess.CalledProcessError as e:
            _fail_and_rollback(
                ReloadFailed, f"systemctl daemon-reload failed: {e}", changes, cause=e
            )
        actions.add("daemon-reload")

    if touched_nginx:
        try:
            runner.run(["sudo", SYSTEMCTL, "reload", "nginx"])
        except subprocess.CalledProcessError as e:
            raise ReloadFailed(
                f"systemctl reload nginx failed: {e}", actions_completed=actions
            ) from e
        actions.add("nginx")

    return actions


def _write_changes(changes: list[Change]) -> None:
    """Apply every write/removal in `changes`. If any single one fails, undo
    everything already applied in this call before re-raising, so a
    mid-batch failure (permissions, disk full) never leaves a partial set of
    changes on disk."""
    applied: list[Change] = []
    try:
        for change in changes:
            if change.is_removal:
                change.path.unlink(missing_ok=True)
            else:
                _write_atomically(change.path, change.after)
            applied.append(change)
    except OSError as e:
        unrestored = _rollback(applied)
        if unrestored:
            e.add_note(
                "additionally, failed to restore: "
                + ", ".join(str(p) for p in unrestored)
                + " — check these by hand"
            )
        raise


def _write_atomically(path: Path, content: str) -> None:
    """Write `content` to `path` without ever leaving a truncated file
    readable at that path: write to a temp file in the same directory, then
    atomically (POSIX `rename`) move it onto the target."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def _rollback(changes: list[Change]) -> list[Path]:
    """Best-effort restore of every change in `changes`.

    Attempts every file even if one fails, so a single un-restorable path
    does not abandon the rest — leaving exactly the half-restored split
    state the callers rely on this function to eliminate. Never raises:
    the caller is always mid-handling of a more important error
    (NginxTestFailed, ReloadFailed, or the original OSError from a failed
    write), and that is what must reach the operator, not a rollback
    failure. Un-restorable paths are reported loudly to stderr, one line
    each, and also returned so the caller can fold them into its own error
    message — that state needs a human either way.
    """
    failed: list[Path] = []
    for change in changes:
        try:
            if change.before is None:
                change.path.unlink(missing_ok=True)
            else:
                _write_atomically(change.path, change.before)
        except OSError as e:
            failed.append(change.path)
            print(f"WARNING: could not restore {change.path}: {e}", file=sys.stderr)
    return failed
